#!/usr/bin/env ruby

puts "-> Configuring Bundler with Chef 10 dependency."
ENV['BUNDLE_GEMFILE'] = File.expand_path('../../gemfile_chef_10', __FILE__)

system "bundle", "install"

puts "-> Configuring Bundler with Chef 11 dependency."
ENV['BUNDLE_GEMFILE'] = File.expand_path('../../gemfile_chef_11', __FILE__)

system "bundle", "install"
