#!/usr/bin/env ruby

ROOT = File.expand_path('../..', __FILE__)

def test_all
  Bundler.setup(:default)

  system "bundle exec rake spec"

  Dir.chdir('examples/simple-solo') do
    system "bundle exec ruby -I#{File.expand_path('lib', ROOT)} -S chef-solo -c solo.rb -j dna.json"
  end
end

puts '-> Testing with Chef 10'

ENV['BUNDLE_GEMFILE'] = File.expand_path('gemfile_chef_10', ROOT)

require "rubygems"
require "bundler/setup"

test_all

puts '-> Testing with Chef 11'

ENV['BUNDLE_GEMFILE'] = File.expand_path('Gemfile', ROOT)

test_all
